# fly.toml app configuration file generated for tabby-server on 2025-01-01T21:19:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tabby-server'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'
  UPSTASH_REDIS_URL = "redis://default:31bff025e9144f22a312d22c23c96c58@us1-engaged-mite-37890.upstash.io:37890"
  REDIS_MAX_RETRIES = "3"
  REDIS_RETRY_DELAY = "1000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
